/** All logos are served from /public/logos/ — local, instant, no CORS */
const club = slug => `/logos/clubs/${slug}.svg`
const comp = slug => `/logos/comps/${slug}.svg`

// ─── TEAMS ────────────────────────────────────────────────────────────────────
export const TEAMS = {
  // ── Premier League ──────────────────────────────────────────────────────────
  'Arsenal':                { logo: club('arsenal'),           home:'#EF0107', away:'#063672', league:'Premier League' },
  'Aston Villa':            { logo: club('aston-villa'),       home:'#95BFE5', away:'#670E36', league:'Premier League' },
  'Bournemouth':            { logo: club('bournemouth'),       home:'#DA291C', away:'#000000', league:'Premier League' },
  'Brentford':              { logo: club('brentford'),         home:'#E30613', away:'#FFFFFF', league:'Premier League' },
  'Brighton':               { logo: club('brighton'),          home:'#0057B8', away:'#FFFFFF', league:'Premier League' },
  'Burnley':                { logo: club('burnley'),           home:'#6C1D45', away:'#99D6EA', league:'Premier League' },
  'Chelsea':                { logo: club('chelsea'),           home:'#034694', away:'#FFFFFF', league:'Premier League' },
  'Crystal Palace':         { logo: club('crystal-palace'),   home:'#1B458F', away:'#C4122E', league:'Premier League' },
  'Everton':                { logo: club('everton'),           home:'#003399', away:'#FFFFFF', league:'Premier League' },
  'Fulham':                 { logo: club('fulham'),            home:'#CC0000', away:'#FFFFFF', league:'Premier League' },
  'Leeds United':           { logo: club('leeds-united'),     home:'#FFCD00', away:'#003090', league:'Premier League' },
  'Liverpool':              { logo: club('liverpool'),         home:'#C8102E', away:'#00B2A9', league:'Premier League' },
  'Manchester City':        { logo: club('manchester-city'),  home:'#6CABDD', away:'#1C2C5B', league:'Premier League' },
  'Manchester United':      { logo: club('manchester-united'),home:'#DA291C', away:'#FBE122', league:'Premier League' },
  'Newcastle United':       { logo: club('newcastle'),        home:'#241F20', away:'#FFFFFF', league:'Premier League' },
  'Nottingham Forest':      { logo: club('nottingham-forest'),home:'#DD0000', away:'#FFFFFF', league:'Premier League' },
  'Sunderland':             { logo: club('sunderland'),       home:'#EB172B', away:'#FFFFFF', league:'Premier League' },
  'Tottenham Hotspur':      { logo: club('tottenham'),        home:'#132257', away:'#FFFFFF', league:'Premier League' },
  'West Ham United':        { logo: club('west-ham'),         home:'#7A263A', away:'#1BB1E7', league:'Premier League' },
  'Wolverhampton':          { logo: club('wolves'),           home:'#FDB913', away:'#231F20', league:'Premier League' },

  // ── Championship ────────────────────────────────────────────────────────────
  'Birmingham City':        { logo: club('birmingham'),            home:'#0000FF', away:'#FFFFFF', league:'Championship' },
  'Blackburn Rovers':       { logo: club('blackburn-rovers'),      home:'#009EE0', away:'#FFFFFF', league:'Championship' },
  'Bristol City':           { logo: club('bristol-city'),          home:'#CC0000', away:'#FFFFFF', league:'Championship' },
  'Charlton Athletic':      { logo: club('charlton'),              home:'#CC0000', away:'#FFFFFF', league:'Championship' },
  'Coventry City':          { logo: club('coventry-city'),         home:'#005BAC', away:'#FFFFFF', league:'Championship' },
  'Derby County':           { logo: club('derby-county'),          home:'#000000', away:'#FFFFFF', league:'Championship' },
  'Hull City':              { logo: club('hull-city'),             home:'#F5A12D', away:'#000000', league:'Championship' },
  'Ipswich Town':           { logo: club('ipswich'),               home:'#0044A9', away:'#FFFFFF', league:'Championship' },
  'Leicester City':         { logo: club('leicester'),             home:'#003090', away:'#FFFFFF', league:'Championship' },
  'Middlesbrough':          { logo: club('middlesbrough'),         home:'#CC0000', away:'#FFFFFF', league:'Championship' },
  'Millwall':               { logo: club('millwall'),              home:'#001D5E', away:'#FFFFFF', league:'Championship' },
  'Norwich City':           { logo: club('norwich-city'),          home:'#00A650', away:'#FFF200', league:'Championship' },
  'Oxford United':          { logo: club('oxford-united'),         home:'#F5A12D', away:'#FFFFFF', league:'Championship' },
  'Portsmouth':             { logo: club('portsmouth'),            home:'#001489', away:'#FFFFFF', league:'Championship' },
  'Preston North End':      { logo: club('preston-north-end'),     home:'#002F6C', away:'#FFFFFF', league:'Championship' },
  'Queens Park Rangers':    { logo: club('queens-park-rangers'),   home:'#005BAC', away:'#FFFFFF', league:'Championship' },
  'Sheffield United':       { logo: club('sheffield-united'),      home:'#EE2737', away:'#FFFFFF', league:'Championship' },
  'Sheffield Wednesday':    { logo: club('sheffield-wednesday'),   home:'#003087', away:'#FFFFFF', league:'Championship' },
  'Southampton':            { logo: club('southampton'),           home:'#D71920', away:'#FFFFFF', league:'Championship' },
  'Stoke City':             { logo: club('stoke-city'),            home:'#E03A3E', away:'#FFFFFF', league:'Championship' },
  'Swansea City':           { logo: club('swansea-city'),          home:'#FFFFFF', away:'#000000', league:'Championship' },
  'Watford':                { logo: club('watford'),               home:'#FBEE23', away:'#CC0000', league:'Championship' },
  'West Brom':              { logo: club('west-bromwich-albion'),  home:'#122F67', away:'#FFFFFF', league:'Championship' },
  'Wrexham':                { logo: club('wrexham'),               home:'#CC0000', away:'#FFFFFF', league:'Championship' },

  // ── La Liga ──────────────────────────────────────────────────────────────────
  'Athletic Club':          { logo: club('athletic-club'),   home:'#EE2523', away:'#FFFFFF', league:'La Liga' },
  'Atletico Madrid':        { logo: club('atletico-madrid'), home:'#CE3524', away:'#1B2265', league:'La Liga' },
  'FC Barcelona':           { logo: club('barcelona'),       home:'#A50044', away:'#004D98', league:'La Liga' },
  'Celta Vigo':             { logo: club('celta'),           home:'#6BBDE3', away:'#FFFFFF', league:'La Liga' },
  'Deportivo':              { logo: club('deportivo'),       home:'#1B3A8A', away:'#FFFFFF', league:'La Liga' },
  'Espanyol':               { logo: club('espanyol'),        home:'#0057A8', away:'#FFFFFF', league:'La Liga' },
  'Getafe':                 { logo: club('getafe'),          home:'#005999', away:'#FFFFFF', league:'La Liga' },
  'Girona':                 { logo: club('girona'),          home:'#CC0000', away:'#FFFFFF', league:'La Liga' },
  'Levante':                { logo: club('levante'),         home:'#0049A0', away:'#FFFFFF', league:'La Liga' },
  'Mallorca':               { logo: club('mallorca'),        home:'#CC0000', away:'#FFFFFF', league:'La Liga' },
  'Osasuna':                { logo: club('osasuna'),         home:'#D00027', away:'#000000', league:'La Liga' },
  'Oviedo':                 { logo: club('oviedo'),          home:'#0049A0', away:'#FFFFFF', league:'La Liga' },
  'Rayo Vallecano':         { logo: club('rayo-vallecano'),  home:'#FFFFFF', away:'#D00027', league:'La Liga' },
  'Real Betis':             { logo: club('real-betis'),      home:'#00954C', away:'#FFFFFF', league:'La Liga' },
  'Real Madrid':            { logo: club('real-madrid'),     home:'#FFFFFF', away:'#9B0000', league:'La Liga' },
  'Real Sociedad':          { logo: club('real-sociedad'),   home:'#0067B1', away:'#FFFFFF', league:'La Liga' },
  'Sevilla':                { logo: club('sevilla'),         home:'#D71920', away:'#FFFFFF', league:'La Liga' },
  'Valencia':               { logo: club('valencia'),        home:'#FFFFFF', away:'#EF7D00', league:'La Liga' },
  'Villarreal':             { logo: club('villarreal'),      home:'#F7D000', away:'#004990', league:'La Liga' },
  'Elche':                  { logo: club('elche'),           home:'#00A650', away:'#FFFFFF', league:'La Liga' },

  // ── Bundesliga ────────────────────────────────────────────────────────────────
  'Augsburg':               { logo: club('augsburg'),              home:'#CC0000', away:'#FFFFFF', league:'Bundesliga' },
  'Bayer Leverkusen':       { logo: club('bayer-leverkusen'),      home:'#E32221', away:'#000000', league:'Bundesliga' },
  'Bayern Munich':          { logo: club('bayern-munchen'),        home:'#DC052D', away:'#FFFFFF', league:'Bundesliga' },
  'Borussia Dortmund':      { logo: club('borussia-dortmund'),     home:'#FDE100', away:'#000000', league:'Bundesliga' },
  'Borussia M\'gladbach':   { logo: club('borussia-monchengladbach'),home:'#000000', away:'#FFFFFF', league:'Bundesliga' },
  'Eintracht Frankfurt':    { logo: club('eintracht-frankfurt'),   home:'#E1000F', away:'#000000', league:'Bundesliga' },
  'FC Heidenheim':          { logo: club('fc-heidenheim'),         home:'#CC0000', away:'#FFFFFF', league:'Bundesliga' },
  'Freiburg':               { logo: club('freiburg'),              home:'#D00027', away:'#FFFFFF', league:'Bundesliga' },
  'Hamburger SV':           { logo: club('hamburger-sv'),          home:'#CC0000', away:'#FFFFFF', league:'Bundesliga' },
  'Hoffenheim':             { logo: club('hoffenheim'),            home:'#1763FF', away:'#FFFFFF', league:'Bundesliga' },
  'Köln':                   { logo: club('koln'),                  home:'#CC0000', away:'#FFFFFF', league:'Bundesliga' },
  'Mainz 05':               { logo: club('mainz-05'),             home:'#CC0000', away:'#FFFFFF', league:'Bundesliga' },
  'RB Leipzig':             { logo: club('rb-leipzig'),            home:'#CC0000', away:'#FFFFFF', league:'Bundesliga' },
  'St. Pauli':              { logo: club('st-pauli'),              home:'#785335', away:'#FFFFFF', league:'Bundesliga' },
  'Union Berlin':           { logo: club('union-berlin'),          home:'#EB1923', away:'#FFFFFF', league:'Bundesliga' },
  'VfB Stuttgart':          { logo: club('vfb-stuttgart'),         home:'#E32221', away:'#FFFFFF', league:'Bundesliga' },
  'Werder Bremen':          { logo: club('werder-bremen'),         home:'#1D9053', away:'#FFFFFF', league:'Bundesliga' },
  'Wolfsburg':              { logo: club('wolfsburg'),             home:'#65B32E', away:'#FFFFFF', league:'Bundesliga' },

  // ── Ligue 1 ──────────────────────────────────────────────────────────────────
  'Angers':                 { logo: club('angers'),            home:'#000000', away:'#FFFFFF', league:'Ligue 1' },
  'AS Monaco':              { logo: club('as-monaco'),         home:'#CE1126', away:'#FFFFFF', league:'Ligue 1' },
  'Auxerre':                { logo: club('auxerre'),           home:'#0033A0', away:'#FFFFFF', league:'Ligue 1' },
  'Brest':                  { logo: club('brest'),             home:'#CC0000', away:'#FFFFFF', league:'Ligue 1' },
  'FC Metz':                { logo: club('fc-metz'),           home:'#8B0000', away:'#FFFFFF', league:'Ligue 1' },
  'Le Havre':               { logo: club('le-havre-ac'),       home:'#0057A8', away:'#FFFFFF', league:'Ligue 1' },
  'Lille':                  { logo: club('lille'),             home:'#C8102E', away:'#FFFFFF', league:'Ligue 1' },
  'Lorient':                { logo: club('lorient'),           home:'#F5A12D', away:'#CC0000', league:'Ligue 1' },
  'Lyon':                   { logo: club('lyon'),              home:'#FFFFFF', away:'#0033A0', league:'Ligue 1' },
  'Marseille':              { logo: club('marseille'),         home:'#2FAEE0', away:'#FFFFFF', league:'Ligue 1' },
  'Nantes':                 { logo: club('nantes'),            home:'#F7D000', away:'#006644', league:'Ligue 1' },
  'Nice':                   { logo: club('nice'),              home:'#000000', away:'#CF0A2C', league:'Ligue 1' },
  'Paris FC':               { logo: club('paris-fc'),          home:'#003087', away:'#FFFFFF', league:'Ligue 1' },
  'PSG':                    { logo: club('paris-saint-germain'),home:'#004170', away:'#DA291C', league:'Ligue 1' },
  'RC Lens':                { logo: club('rc-lens'),           home:'#FFD700', away:'#CC0000', league:'Ligue 1' },
  'RC Strasbourg':          { logo: club('rc-strasbourg-alsace'),home:'#0070B8', away:'#FFFFFF', league:'Ligue 1' },
  'Rennes':                 { logo: club('rennes'),            home:'#DA291C', away:'#000000', league:'Ligue 1' },
  'Toulouse':               { logo: club('toulouse'),          home:'#78003C', away:'#FFFFFF', league:'Ligue 1' },

  // ── Serie A ──────────────────────────────────────────────────────────────────
  'AC Milan':               { logo: club('milan'),       home:'#FB090B', away:'#000000', league:'Serie A' },
  'Atalanta':               { logo: club('atalanta'),    home:'#1E3A8A', away:'#000000', league:'Serie A' },
  'Bologna':                { logo: club('bologna'),     home:'#CC0000', away:'#1B306E', league:'Serie A' },
  'Cagliari':               { logo: club('cagliari'),    home:'#CC0000', away:'#003087', league:'Serie A' },
  'Como 1907':              { logo: club('como-1907'),   home:'#0049A0', away:'#FFFFFF', league:'Serie A' },
  'Cremonese':              { logo: club('cremonese'),   home:'#CC0000', away:'#FFFFFF', league:'Serie A' },
  'Fiorentina':             { logo: club('fiorentina'),  home:'#522D8B', away:'#FFFFFF', league:'Serie A' },
  'Genoa':                  { logo: club('genoa'),       home:'#CC0000', away:'#003087', league:'Serie A' },
  'Inter Milan':            { logo: club('inter'),       home:'#010E80', away:'#000000', league:'Serie A' },
  'Juventus':               { logo: club('juventus'),    home:'#000000', away:'#FFFFFF', league:'Serie A' },
  'Lazio':                  { logo: club('lazio'),       home:'#87CEEB', away:'#FFFFFF', league:'Serie A' },
  'Lecce':                  { logo: club('lecce'),       home:'#FFD700', away:'#CC0000', league:'Serie A' },
  'Napoli':                 { logo: club('napoli'),      home:'#12A0C3', away:'#FFFFFF', league:'Serie A' },
  'Parma':                  { logo: club('parma'),       home:'#FFD700', away:'#003087', league:'Serie A' },
  'Pisa':                   { logo: club('pisa'),        home:'#000080', away:'#FFFFFF', league:'Serie A' },
  'AS Roma':                { logo: club('roma'),        home:'#A90005', away:'#FFD700', league:'Serie A' },
  'Sassuolo':               { logo: club('sassuolo'),    home:'#00643C', away:'#000000', league:'Serie A' },
  'Torino':                 { logo: club('torino'),      home:'#8B0000', away:'#FFFFFF', league:'Serie A' },
  'Udinese':                { logo: club('udinese'),     home:'#000000', away:'#FFFFFF', league:'Serie A' },
  'Verona':                 { logo: club('verona'),      home:'#003087', away:'#FFD700', league:'Serie A' },

  // ── Eredivisie ────────────────────────────────────────────────────────────────
  'Ajax':                   { logo: club('ajax'),               home:'#CC0000', away:'#FFFFFF', league:'Eredivisie' },
  'AZ Alkmaar':             { logo: club('az-alkmaar'),         home:'#CC0000', away:'#FFFFFF', league:'Eredivisie' },
  'Excelsior Rotterdam':    { logo: club('excelsior-rotterdam'),home:'#CC0000', away:'#FFFFFF', league:'Eredivisie' },
  'FC Groningen':           { logo: club('fc-groningen'),       home:'#006644', away:'#FFFFFF', league:'Eredivisie' },
  'FC Utrecht':             { logo: club('fc-utrecht'),         home:'#CC0000', away:'#FFFFFF', league:'Eredivisie' },
  'Feyenoord':              { logo: club('feyenoord'),          home:'#CC0000', away:'#FFFFFF', league:'Eredivisie' },
  'Fortuna Sittard':        { logo: club('fortuna-sittard'),    home:'#FFD700', away:'#CC0000', league:'Eredivisie' },
  'Go Ahead Eagles':        { logo: club('go-ahead-eagles'),    home:'#CC0000', away:'#FFD700', league:'Eredivisie' },
  'Heracles Almelo':        { logo: club('heracles-almelo'),    home:'#CC0000', away:'#FFFFFF', league:'Eredivisie' },
  'NAC Breda':              { logo: club('nac-breda'),          home:'#FFD700', away:'#000000', league:'Eredivisie' },
  'NEC Nijmegen':           { logo: club('nec-nijmegen'),       home:'#CC0000', away:'#FFFFFF', league:'Eredivisie' },
  'PEC Zwolle':             { logo: club('pec-zwolle'),         home:'#003087', away:'#FFFFFF', league:'Eredivisie' },
  'PSV':                    { logo: club('psv'),                home:'#CC0000', away:'#FFFFFF', league:'Eredivisie' },
  'SC Heerenveen':          { logo: club('sc-heerenveen'),      home:'#003087', away:'#FFFFFF', league:'Eredivisie' },
  'Sparta Rotterdam':       { logo: club('sparta-rotterdam'),   home:'#CC0000', away:'#FFFFFF', league:'Eredivisie' },
  'Twente':                 { logo: club('twente'),             home:'#CC0000', away:'#FFFFFF', league:'Eredivisie' },
  'Volendam':               { logo: club('volendam'),           home:'#F5A12D', away:'#CC0000', league:'Eredivisie' },

  // ── Primeira Liga ────────────────────────────────────────────────────────────
  'Benfica':                { logo: club('benfica'),          home:'#CC0000', away:'#FFFFFF', league:'Primeira Liga' },
  'SC Braga':               { logo: club('sc-braga'),         home:'#CC0000', away:'#FFFFFF', league:'Primeira Liga' },
  'FC Porto':               { logo: club('fc-porto'),         home:'#004899', away:'#FFFFFF', league:'Primeira Liga' },
  'Sporting CP':            { logo: club('sporting-cp'),      home:'#006600', away:'#FFFFFF', league:'Primeira Liga' },
  'Alverca':                { logo: club('alverca'),          home:'#CC0000', away:'#FFFFFF', league:'Primeira Liga' },
  'Arouca':                 { logo: club('arouca'),           home:'#006644', away:'#FFFFFF', league:'Primeira Liga' },
  'Estoril':                { logo: club('estoril'),          home:'#FFD700', away:'#000000', league:'Primeira Liga' },
  'Famalicao':              { logo: club('famalicao'),        home:'#CC0000', away:'#FFFFFF', league:'Primeira Liga' },
  'Gil Vicente':            { logo: club('gil-vicente'),      home:'#000080', away:'#FFFFFF', league:'Primeira Liga' },
  'Moreirense':             { logo: club('moreirense'),       home:'#006644', away:'#FFFFFF', league:'Primeira Liga' },
  'Rio Ave':                { logo: club('rio-ave'),          home:'#006644', away:'#FFFFFF', league:'Primeira Liga' },
  'Santa Clara':            { logo: club('santa-clara'),      home:'#CC0000', away:'#FFFFFF', league:'Primeira Liga' },
  'Vitoria Guimaraes':      { logo: club('vitoria-de-guimaraes'),home:'#006644', away:'#FFFFFF', league:'Primeira Liga' },

  // ── Scottish Premiership ──────────────────────────────────────────────────────
  'Aberdeen':               { logo: club('aberdeen'),      home:'#CC0000', away:'#FFFFFF', league:'Scottish Prem' },
  'Celtic':                 { logo: club('celtic'),        home:'#1A7A37', away:'#FFFFFF', league:'Scottish Prem' },
  'Dundee':                 { logo: club('dundee'),        home:'#003087', away:'#FFFFFF', league:'Scottish Prem' },
  'Dundee United':          { logo: club('dundee-united'), home:'#F5A12D', away:'#000000', league:'Scottish Prem' },
  'Falkirk':                { logo: club('falkirk'),       home:'#003087', away:'#FFFFFF', league:'Scottish Prem' },
  'Hearts':                 { logo: club('hearts'),        home:'#A50034', away:'#FFFFFF', league:'Scottish Prem' },
  'Hibernian':              { logo: club('hibernian'),     home:'#005000', away:'#FFFFFF', league:'Scottish Prem' },
  'Kilmarnock':             { logo: club('kilmarnock'),    home:'#003087', away:'#FFFFFF', league:'Scottish Prem' },
  'Livingston':             { logo: club('livingston'),    home:'#FFD700', away:'#000000', league:'Scottish Prem' },
  'Motherwell':             { logo: club('motherwell'),    home:'#CC0000', away:'#FFFFFF', league:'Scottish Prem' },
  'Rangers':                { logo: club('rangers'),       home:'#1B3A8A', away:'#FFFFFF', league:'Scottish Prem' },
  'St Mirren':              { logo: club('st-mirren'),     home:'#000000', away:'#FFFFFF', league:'Scottish Prem' },

  // ── Turkish Süper Lig ────────────────────────────────────────────────────────
  'Alanyaspor':             { logo: club('alanyaspor'),        home:'#F5A12D', away:'#CC0000', league:'Süper Lig' },
  'Antalyaspor':            { logo: club('antalyaspor'),       home:'#CC0000', away:'#FFFFFF', league:'Süper Lig' },
  'Basaksehir':             { logo: club('basaksehir'),        home:'#F5A12D', away:'#CC0000', league:'Süper Lig' },
  'Besiktas':               { logo: club('besiktas'),          home:'#000000', away:'#FFFFFF', league:'Süper Lig' },
  'Eyupspor':               { logo: club('eyupspor'),          home:'#CC0000', away:'#FFFFFF', league:'Süper Lig' },
  'Fatih Karagumruk':       { logo: club('fatih-karagumruk'),  home:'#CC0000', away:'#FFFFFF', league:'Süper Lig' },
  'Fenerbahce':             { logo: club('fenerbahce'),        home:'#FFD700', away:'#002B56', league:'Süper Lig' },
  'Galatasaray':            { logo: club('galatasaray'),       home:'#FF6600', away:'#CC0000', league:'Süper Lig' },
  'Gaziantep':              { logo: club('gaziantep'),         home:'#CC0000', away:'#FFFFFF', league:'Süper Lig' },
  'Genclerbirligi':         { logo: club('genclerbirligi'),    home:'#CC0000', away:'#FFFFFF', league:'Süper Lig' },
  'Goztepe Izmir':          { logo: club('goztepe-izmir'),     home:'#F5A12D', away:'#CC0000', league:'Süper Lig' },
  'Kasimpasa':              { logo: club('kasimpasa'),         home:'#006644', away:'#FFFFFF', league:'Süper Lig' },
  'Kayserispor':            { logo: club('kayserispor'),       home:'#CC0000', away:'#FFD700', league:'Süper Lig' },
  'Kocaelispor':            { logo: club('kocaelispor'),       home:'#CC0000', away:'#FFFFFF', league:'Süper Lig' },
  'Konyaspor':              { logo: club('konyaspor'),         home:'#006644', away:'#FFFFFF', league:'Süper Lig' },
  'Rizespor':               { logo: club('rizespor'),          home:'#006644', away:'#FFFFFF', league:'Süper Lig' },
  'Samsunspor':             { logo: club('samsunspor'),        home:'#CC0000', away:'#FFFFFF', league:'Süper Lig' },
  'Trabzonspor':            { logo: club('trabzonspor'),       home:'#A0522D', away:'#003087', league:'Süper Lig' },

  // ── Saudi Pro League ─────────────────────────────────────────────────────────
  'Al-Ahli':                { logo: club('al-ahli'),     home:'#006644', away:'#FFFFFF', league:'Saudi Pro League' },
  'Al-Ettifaq':             { logo: club('al-ettifaq'),  home:'#F5A12D', away:'#000000', league:'Saudi Pro League' },
  'Al-Fateh':               { logo: club('al-fateh'),    home:'#CC0000', away:'#FFFFFF', league:'Saudi Pro League' },
  'Al-Hilal':               { logo: club('al-hilal'),    home:'#003087', away:'#FFFFFF', league:'Saudi Pro League' },
  'Al-Ittihad':             { logo: club('al-ittihad'),  home:'#FFD700', away:'#000000', league:'Saudi Pro League' },
  'Al-Nassr':               { logo: club('al-nassr'),    home:'#FFD700', away:'#006644', league:'Saudi Pro League' },
  'Al-Shabab':              { logo: club('al-shabab'),   home:'#006644', away:'#FFFFFF', league:'Saudi Pro League' },
  'Al-Taawoun':             { logo: club('al-taawoun'),  home:'#FFD700', away:'#006644', league:'Saudi Pro League' },
  'Damac':                  { logo: club('damac'),       home:'#FFD700', away:'#000000', league:'Saudi Pro League' },
  'NEOM':                   { logo: club('neom'),        home:'#003087', away:'#FFFFFF', league:'Saudi Pro League' },

  // ── MLS ───────────────────────────────────────────────────────────────────────
  'Atlanta United':         { logo: club('atlanta-united'),        home:'#CC0000', away:'#000000', league:'MLS' },
  'Austin FC':              { logo: club('austins-fc'),            home:'#006644', away:'#000000', league:'MLS' },
  'CF Montréal':            { logo: club('cf-montreal'),           home:'#003087', away:'#FFFFFF', league:'MLS' },
  'Charlotte FC':           { logo: club('charlotte-fc'),          home:'#1A75CF', away:'#FFFFFF', league:'MLS' },
  'Chicago Fire':           { logo: club('chicago-fire-fc'),       home:'#CC0000', away:'#FFFFFF', league:'MLS' },
  'Colorado Rapids':        { logo: club('colorado-rapids'),       home:'#862633', away:'#FFFFFF', league:'MLS' },
  'Columbus Crew':          { logo: club('columbus-crew'),         home:'#FFD700', away:'#000000', league:'MLS' },
  'DC United':              { logo: club('dc-united'),             home:'#000000', away:'#FFFFFF', league:'MLS' },
  'FC Cincinnati':          { logo: club('fc-cincinnati'),         home:'#003087', away:'#F05323', league:'MLS' },
  'FC Dallas':              { logo: club('fc-dallas'),             home:'#CC0000', away:'#003087', league:'MLS' },
  'Houston Dynamo':         { logo: club('houston-dynamo'),        home:'#F5A12D', away:'#000000', league:'MLS' },
  'Inter Miami CF':         { logo: club('inter-miami-cf'),        home:'#F7B5CD', away:'#000000', league:'MLS' },
  'LA Galaxy':              { logo: club('la-galaxy'),             home:'#FFD700', away:'#002F6C', league:'MLS' },
  'LAFC':                   { logo: club('los-angeles-fc'),        home:'#C39E6D', away:'#000000', league:'MLS' },
  'Minnesota United':       { logo: club('minnesota-united-fc'),   home:'#8CD2F4', away:'#231F20', league:'MLS' },
  'Nashville SC':           { logo: club('nashville-sc'),          home:'#ECE83A', away:'#001A30', league:'MLS' },
  'New England Revolution': { logo: club('new-england-revolution'),home:'#CC0000', away:'#003087', league:'MLS' },
  'NYCFC':                  { logo: club('new-york-city-fc'),      home:'#6CABDD', away:'#003087', league:'MLS' },
  'New York Red Bulls':     { logo: club('new-york-red-bulls'),    home:'#CC0000', away:'#FFFFFF', league:'MLS' },
  'Orlando City':           { logo: club('orlando-city'),          home:'#5C2D91', away:'#FFD700', league:'MLS' },
  'Philadelphia Union':     { logo: club('philadelphia-union'),    home:'#071B2C', away:'#FFFFFF', league:'MLS' },
  'Portland Timbers':       { logo: club('portland-timbers'),      home:'#004812', away:'#FFD700', league:'MLS' },
  'Real Salt Lake':         { logo: club('real-salt-lake'),        home:'#B30838', away:'#FFFFFF', league:'MLS' },
  'San Diego FC':           { logo: club('san-diego-fc'),          home:'#003087', away:'#FFFFFF', league:'MLS' },
  'San Jose Earthquakes':   { logo: club('san-jose-earthquakes'),  home:'#0067B1', away:'#000000', league:'MLS' },
  'Seattle Sounders':       { logo: club('seattle-sounders-fc'),   home:'#5D9741', away:'#003087', league:'MLS' },
  'Sporting KC':            { logo: club('sporting-kansas-city'),  home:'#93B4D9', away:'#002F6C', league:'MLS' },
  'St. Louis City SC':      { logo: club('st-louis-city-sc'),      home:'#CC0000', away:'#FFFFFF', league:'MLS' },
  'Toronto FC':             { logo: club('toronto-fc'),            home:'#CC0000', away:'#FFFFFF', league:'MLS' },
  'Vancouver Whitecaps':    { logo: club('vancouver-whitecaps-fc'),home:'#001B5E', away:'#FFFFFF', league:'MLS' },

  // ── UCL extra clubs ────────────────────────────────────────────────────────
  'Bodo/Glimt':             { logo: club('bodo-glimt'),      home:'#FFD700', away:'#000000', league:'Champions League' },
  'Club Brugge':            { logo: club('club-brugge'),     home:'#003087', away:'#000000', league:'Champions League' },
  'Copenhagen':             { logo: club('copenhagen'),      home:'#003087', away:'#FFFFFF', league:'Champions League' },
  'Olympiacos':             { logo: club('olympiacos'),      home:'#CC0000', away:'#FFFFFF', league:'Champions League' },
  'Qarabag':                { logo: club('qarabag'),         home:'#000000', away:'#CC0000', league:'Champions League' },
  'Slavia Praha':           { logo: club('slavia-praha'),    home:'#CC0000', away:'#FFFFFF', league:'Champions League' },
  'Union St-Gilloise':      { logo: club('union-saint-gilloise'),home:'#FFD700', away:'#003087', league:'Champions League' },
  'Shakhtar Donetsk':       { logo: club('shakhtar'),        home:'#FF6600', away:'#000000', league:'Europa League' },
  'Dinamo Zagreb':          { logo: club('dinamo-zagreb'),   home:'#0049A0', away:'#FFFFFF', league:'Europa League' },
  'Red Bull Salzburg':      { logo: club('salzburg'),        home:'#CC0000', away:'#FFFFFF', league:'Europa League' },
  'Young Boys':             { logo: club('young-boys'),      home:'#FFD700', away:'#000000', league:'Europa League' },
  'Crvena Zvezda':          { logo: club('crvena-zvezda'),   home:'#CC0000', away:'#FFFFFF', league:'Europa League' },
  'Feyenoord':              { logo: club('feyenoord'),       home:'#CC0000', away:'#FFFFFF', league:'Europa League' },
}

// ─── COMPETITIONS ─────────────────────────────────────────────────────────────
export const COMPETITIONS = {
  'UEFA Champions League':  { logo: comp('tournaments_uefa-champions-league'),  color:'#001D62', bg:'#001230' },
  'UEFA Europa League':     { logo: comp('tournaments_uefa-europa-league'),     color:'#FF6B00', bg:'#1a0d00' },
  'UEFA Conference League': { logo: comp('tournaments_uefa-conference-league'), color:'#00A551', bg:'#001a0e' },
  'Premier League':         { logo: comp('england_english-premier-league'),     color:'#3D195B', bg:'#0d0014' },
  'La Liga':                { logo: comp('spain_la-liga'),                      color:'#EE8707', bg:'#1a0c00' },
  'Bundesliga':             { logo: comp('germany_bundesliga'),                 color:'#D3010C', bg:'#1a0000' },
  'Serie A':                { logo: comp('italy_serie-a'),                      color:'#024494', bg:'#000b1a' },
  'Ligue 1':                { logo: comp('france_ligue-1'),                     color:'#DFFE00', bg:'#0d0d00' },
  'FA Cup':                 { logo: comp('england_emirates-fa-cup'),             color:'#00294A', bg:'#000e1a' },
  'EFL Cup':                { logo: comp('england_efl-cup'),                    color:'#00A0C6', bg:'#001419' },
  'EFL Championship':       { logo: comp('england_efl-championship'),           color:'#003087', bg:'#000b1a' },
  'Copa del Rey':           { logo: comp('spain_copa-del-rey'),                 color:'#AA151B', bg:'#1a0203' },
  'DFB Pokal':              { logo: comp('germany_dfb-pokal'),                  color:'#000000', bg:'#0a0a0a' },
  'Coppa Italia':           { logo: comp('italy_coppa-italia'),                 color:'#009246', bg:'#001a09' },
  'Eredivisie':             { logo: comp('netherlands_eredivisie'),             color:'#CC0000', bg:'#1a0000' },
  'UEFA Super Cup':         { logo: comp('tournaments_uefa-super-cup'),         color:'#001D62', bg:'#001230' },
  'UEFA Nations League':    { logo: comp('tournaments_uefa-nations-league'),    color:'#001D62', bg:'#001230' },
  'FIFA Club World Cup':    { logo: comp('tournaments_fifa-club-world-cup'),    color:'#003087', bg:'#000b1a' },
  'FIFA World Cup 2026':    { logo: comp('tournaments_fifa-world-cup-2026'),    color:'#003087', bg:'#000b1a' },
  'CONMEBOL Libertadores':  { logo: comp('tournaments_conmebol-libertadores'),  color:'#003087', bg:'#000b1a' },
  'Supercopa de España':    { logo: comp('spain_supercopa-de-espana'),          color:'#AA151B', bg:'#1a0203' },
  'FA Community Shield':    { logo: comp('england_fa-community-shield'),        color:'#00294A', bg:'#000e1a' },
}

export const TEAM_NAMES       = Object.keys(TEAMS).sort()
export const COMPETITION_NAMES = Object.keys(COMPETITIONS)

export const MATCH_STAGES = [
  'Matchday', 'Group Stage', 'Round of 32', 'Round of 16',
  'Quarter Final', 'Semi Final', 'Final', 'Play-Off',
  'League Match', 'Cup Round', 'Super Cup',
]

export function getTeam(name)        { return TEAMS[name]        || { logo:null, home:'#e0000a', away:'#ffffff' } }
export function getCompetition(name) { return COMPETITIONS[name] || { logo:null, color:'#e0000a', bg:'#0d0d14'  } }
