// All logos are local SVGs in /public/logos/ — no CORS, instant load, works in PNG export
const club = s => `/logos/clubs/${s}.svg`
const comp = s => `/logos/comps/${s}.svg`

// ── TEAMS ─────────────────────────────────────────────────────
// { logo, home (kit color), away, bg }
export const TEAMS = {
  // Premier League
  'Arsenal':               { logo: club('arsenal'),           home: '#EF0107', away: '#063672', bg: '#1a0505' },
  'Aston Villa':           { logo: club('aston-villa'),       home: '#670E36', away: '#95BFE5', bg: '#0e0514' },
  'Bournemouth':           { logo: club('bournemouth'),       home: '#DA291C', away: '#000000', bg: '#1a0202' },
  'Brentford':             { logo: club('brentford'),         home: '#E30613', away: '#FFFFFF', bg: '#1a0505' },
  'Brighton':              { logo: club('brighton'),          home: '#0057B8', away: '#FFFFFF', bg: '#020d1a' },
  'Burnley':               { logo: club('burnley'),           home: '#6C1D45', away: '#99D6EA', bg: '#12040c' },
  'Chelsea':               { logo: club('chelsea'),           home: '#034694', away: '#FFFFFF', bg: '#00071a' },
  'Crystal Palace':        { logo: club('crystal-palace'),    home: '#1B458F', away: '#C4122E', bg: '#00071a' },
  'Everton':               { logo: club('everton'),           home: '#003399', away: '#FFFFFF', bg: '#00051a' },
  'Fulham':                { logo: club('fulham'),            home: '#CC0000', away: '#FFFFFF', bg: '#1a0000' },
  'Leeds United':          { logo: club('leeds-united'),      home: '#FFFFFF', away: '#1D428A', bg: '#0d0d0d' },
  'Liverpool':             { logo: club('liverpool'),         home: '#C8102E', away: '#00B2A9', bg: '#1a0005' },
  'Manchester City':       { logo: club('manchester-city'),   home: '#6CABDD', away: '#1C2C5B', bg: '#030d1a' },
  'Manchester United':     { logo: club('manchester-united'), home: '#DA291C', away: '#FBE122', bg: '#1a0302' },
  'Newcastle United':      { logo: club('newcastle'),         home: '#241F20', away: '#FFFFFF', bg: '#0a0a0a' },
  'Nottingham Forest':     { logo: club('nottingham-forest'), home: '#DD0000', away: '#FFFFFF', bg: '#1a0000' },
  'Sunderland':            { logo: club('sunderland'),        home: '#EB172B', away: '#FFFFFF', bg: '#1a0202' },
  'Tottenham Hotspur':     { logo: club('tottenham'),         home: '#132257', away: '#FFFFFF', bg: '#010410' },
  'West Ham United':       { logo: club('west-ham'),          home: '#7A263A', away: '#1BB1E7', bg: '#12040b' },
  'Wolves':                { logo: club('wolves'),            home: '#FDB913', away: '#231F20', bg: '#1a1100' },

  // Championship
  'Birmingham City':       { logo: club('birmingham'),        home: '#0000FF', away: '#FFFFFF', bg: '#00001a' },
  'Blackburn Rovers':      { logo: club('blackburn-rovers'),  home: '#009EE0', away: '#FFFFFF', bg: '#031419' },
  'Bristol City':          { logo: club('bristol-city'),      home: '#E00000', away: '#FFFFFF', bg: '#1a0000' },
  'Charlton Athletic':     { logo: club('charlton'),          home: '#CC0000', away: '#FFFFFF', bg: '#1a0000' },
  'Coventry City':         { logo: club('coventry-city'),     home: '#59CBED', away: '#FFFFFF', bg: '#031419' },
  'Derby County':          { logo: club('derby-county'),      home: '#FFFFFF', away: '#000000', bg: '#0d0d0d' },
  'Hull City':             { logo: club('hull-city'),         home: '#F5A12D', away: '#000000', bg: '#1a1000' },
  'Ipswich Town':          { logo: club('ipswich'),           home: '#0044A9', away: '#FFFFFF', bg: '#00051a' },
  'Leicester City':        { logo: club('leicester'),         home: '#003090', away: '#FFFFFF', bg: '#00031a' },
  'Middlesbrough':         { logo: club('middlesbrough'),     home: '#E00000', away: '#FFFFFF', bg: '#1a0000' },
  'Millwall':              { logo: club('millwall'),          home: '#001D5E', away: '#FFFFFF', bg: '#00011a' },
  'Norwich City':          { logo: club('norwich-city'),      home: '#00A650', away: '#FFF200', bg: '#001400' },
  'Oxford United':         { logo: club('oxford-united'),     home: '#F5A500', away: '#000000', bg: '#1a1000' },
  'Portsmouth':            { logo: club('portsmouth'),        home: '#001489', away: '#FFFFFF', bg: '#00011a' },
  'Preston North End':     { logo: club('preston-north-end'), home: '#FFFFFF', away: '#000000', bg: '#0d0d0d' },
  'QPR':                   { logo: club('queens-park-rangers'),home:'#005CAB',away: '#FFFFFF',  bg: '#00041a' },
  'Sheffield United':      { logo: club('sheffield-united'),  home: '#EE2737', away: '#FFFFFF', bg: '#1a0205' },
  'Sheffield Wednesday':   { logo: club('sheffield-wednesday'),home:'#0066B3',away:'#FFFFFF',   bg: '#00081a' },
  'Southampton':           { logo: club('southampton'),       home: '#D71920', away: '#FFFFFF', bg: '#1a0203' },
  'Stoke City':            { logo: club('stoke-city'),        home: '#E03A3E', away: '#FFFFFF', bg: '#1a0202' },
  'Swansea City':          { logo: club('swansea-city'),      home: '#FFFFFF', away: '#000000', bg: '#0d0d0d' },
  'Watford':               { logo: club('watford'),           home: '#FBEE23', away: '#CC0000', bg: '#1a1300' },
  'West Brom':             { logo: club('west-bromwich-albion'),home:'#122F67',away:'#FFFFFF',  bg: '#00021a' },
  'Wrexham':               { logo: club('wrexham'),           home: '#CC0000', away: '#FFFFFF', bg: '#1a0000' },

  // La Liga
  'Athletic Club':         { logo: club('athletic-club'),     home: '#EE2523', away: '#FFFFFF', bg: '#1a0202' },
  'Atletico Madrid':       { logo: club('atletico-madrid'),   home: '#CE3524', away: '#1B2265', bg: '#1a0302' },
  'FC Barcelona':          { logo: club('barcelona'),         home: '#A50044', away: '#004D98', bg: '#140008' },
  'Celta Vigo':            { logo: club('celta'),             home: '#6BBDE3', away: '#FFFFFF', bg: '#030d14' },
  'Deportivo':             { logo: club('deportivo'),         home: '#1B1464', away: '#FFFFFF', bg: '#00011a' },
  'Elche':                 { logo: club('elche'),             home: '#00873E', away: '#FFFFFF', bg: '#001a0d' },
  'Espanyol':              { logo: club('espanyol'),          home: '#004B9C', away: '#FFFFFF', bg: '#00041a' },
  'Getafe':                { logo: club('getafe'),            home: '#005999', away: '#FFFFFF', bg: '#000e1a' },
  'Girona':                { logo: club('girona'),            home: '#CC0000', away: '#FFFFFF', bg: '#1a0000' },
  'Levante':               { logo: club('levante'),           home: '#004B9C', away: '#CC0000', bg: '#00041a' },
  'Mallorca':              { logo: club('mallorca'),          home: '#CC0000', away: '#000000', bg: '#1a0000' },
  'Osasuna':               { logo: club('osasuna'),           home: '#D00027', away: '#000000', bg: '#1a0003' },
  'Oviedo':                { logo: club('oviedo'),            home: '#003594', away: '#FFFFFF', bg: '#00031a' },
  'Rayo Vallecano':        { logo: club('rayo-vallecano'),    home: '#FFFFFF', away: '#D00027', bg: '#0d0d0d' },
  'Real Betis':            { logo: club('real-betis'),        home: '#00954C', away: '#FFFFFF', bg: '#001a0e' },
  'Real Madrid':           { logo: club('real-madrid'),       home: '#FFFFFF', away: '#9B0000', bg: '#0d0d0d' },
  'Real Sociedad':         { logo: club('real-sociedad'),     home: '#0067B1', away: '#FFFFFF', bg: '#00091a' },
  'Sevilla':               { logo: club('sevilla'),           home: '#D71920', away: '#FFFFFF', bg: '#1a0203' },
  'Valencia':              { logo: club('valencia'),          home: '#FFFFFF', away: '#EF7D00', bg: '#0d0d0d' },
  'Villarreal':            { logo: club('villarreal'),        home: '#F7D000', away: '#004990', bg: '#1a1300' },

  // Bundesliga
  'Augsburg':              { logo: club('augsburg'),          home: '#BA0303', away: '#FFFFFF', bg: '#1a0000' },
  'Bayer Leverkusen':      { logo: club('bayer-leverkusen'),  home: '#E32221', away: '#000000', bg: '#1a0202' },
  'Bayern Munich':         { logo: club('bayern-munchen'),    home: '#DC052D', away: '#FFFFFF', bg: '#1a0003' },
  'Borussia Dortmund':     { logo: club('borussia-dortmund'), home: '#FDE100', away: '#000000', bg: '#1a1300' },
  "Borussia M'gladbach":   { logo: club('borussia-monchengladbach'), home: '#000000', away: '#FFFFFF', bg: '#0a0a0a' },
  'Eintracht Frankfurt':   { logo: club('eintracht-frankfurt'), home: '#E1000F', away: '#000000', bg: '#1a0202' },
  'FC Heidenheim':         { logo: club('fc-heidenheim'),     home: '#CC0000', away: '#FFFFFF', bg: '#1a0000' },
  'Freiburg':              { logo: club('freiburg'),          home: '#D00027', away: '#FFFFFF', bg: '#1a0003' },
  'Hamburger SV':          { logo: club('hamburger-sv'),      home: '#005CA9', away: '#FFFFFF', bg: '#00041a' },
  'Hoffenheim':            { logo: club('hoffenheim'),        home: '#1763FF', away: '#FFFFFF', bg: '#00081a' },
  'Köln':                  { logo: club('koln'),              home: '#CC0000', away: '#FFFFFF', bg: '#1a0000' },
  'Mainz 05':              { logo: club('mainz-05'),          home: '#CC0000', away: '#FFFFFF', bg: '#1a0000' },
  'RB Leipzig':            { logo: club('rb-leipzig'),        home: '#CC0000', away: '#FFFFFF', bg: '#1a0000' },
  'St. Pauli':             { logo: club('st-pauli'),          home: '#70402C', away: '#FFFFFF', bg: '#130a07' },
  'Union Berlin':          { logo: club('union-berlin'),      home: '#CC0000', away: '#FFFFFF', bg: '#1a0000' },
  'VfB Stuttgart':         { logo: club('vfb-stuttgart'),     home: '#E32221', away: '#FFFFFF', bg: '#1a0202' },
  'Werder Bremen':         { logo: club('werder-bremen'),     home: '#1D9B4B', away: '#FFFFFF', bg: '#01140a' },
  'Wolfsburg':             { logo: club('wolfsburg'),         home: '#65B32E', away: '#FFFFFF', bg: '#041200' },

  // Serie A
  'Atalanta':              { logo: club('atalanta'),          home: '#1E3A8A', away: '#000000', bg: '#000c1a' },
  'Bologna':               { logo: club('bologna'),           home: '#CC0000', away: '#1B306E', bg: '#1a0000' },
  'Cagliari':              { logo: club('cagliari'),          home: '#CC0000', away: '#004B9C', bg: '#1a0000' },
  'Como 1907':             { logo: club('como-1907'),         home: '#003DA5', away: '#FFFFFF', bg: '#00041a' },
  'Cremonese':             { logo: club('cremonese'),         home: '#CC0000', away: '#FFFFFF', bg: '#1a0000' },
  'Fiorentina':            { logo: club('fiorentina'),        home: '#522D8B', away: '#FFFFFF', bg: '#0d0016' },
  'Genoa':                 { logo: club('genoa'),             home: '#CC0000', away: '#003087', bg: '#1a0000' },
  'Inter Milan':           { logo: club('inter'),             home: '#010E80', away: '#000000', bg: '#00011a' },
  'Juventus':              { logo: club('juventus'),          home: '#000000', away: '#FFFFFF', bg: '#0a0a0a' },
  'Lazio':                 { logo: club('lazio'),             home: '#87CEEB', away: '#FFFFFF', bg: '#031218' },
  'Lecce':                 { logo: club('lecce'),             home: '#FFD700', away: '#CC0000', bg: '#1a1300' },
  'AC Milan':              { logo: club('milan'),             home: '#FB090B', away: '#000000', bg: '#1a0202' },
  'Napoli':                { logo: club('napoli'),            home: '#12A0C3', away: '#FFFFFF', bg: '#011419' },
  'Parma':                 { logo: club('parma'),             home: '#FFD700', away: '#003DA5', bg: '#1a1300' },
  'Pisa':                  { logo: club('pisa'),              home: '#003DA5', away: '#000000', bg: '#00041a' },
  'AS Roma':               { logo: club('roma'),              home: '#A90005', away: '#FFD700', bg: '#1a0001' },
  'Sassuolo':              { logo: club('sassuolo'),          home: '#00703C', away: '#000000', bg: '#001400' },
  'Torino':                { logo: club('torino'),            home: '#8B0000', away: '#FFFFFF', bg: '#120000' },
  'Udinese':               { logo: club('udinese'),           home: '#000000', away: '#FFFFFF', bg: '#0a0a0a' },
  'Verona':                { logo: club('verona'),            home: '#003DA5', away: '#FFD700', bg: '#00031a' },

  // Ligue 1
  'Angers':                { logo: club('angers'),            home: '#000000', away: '#FFFFFF', bg: '#0a0a0a' },
  'Monaco':                { logo: club('as-monaco'),         home: '#CE1126', away: '#FFFFFF', bg: '#1a0203' },
  'Auxerre':               { logo: club('auxerre'),           home: '#003DA5', away: '#FFFFFF', bg: '#00041a' },
  'Brest':                 { logo: club('brest'),             home: '#CC0000', away: '#FFFFFF', bg: '#1a0000' },
  'FC Metz':               { logo: club('fc-metz'),           home: '#7A003C', away: '#FFD700', bg: '#120008' },
  'Le Havre':              { logo: club('le-havre-ac'),       home: '#003DA5', away: '#FFFFFF', bg: '#00041a' },
  'Lille':                 { logo: club('lille'),             home: '#C8102E', away: '#FFFFFF', bg: '#1a0203' },
  'Lorient':               { logo: club('lorient'),           home: '#F7A600', away: '#000000', bg: '#1a1000' },
  'Lyon':                  { logo: club('lyon'),              home: '#FFFFFF', away: '#0033A0', bg: '#0d0d0d' },
  'Marseille':             { logo: club('marseille'),         home: '#2FAEE0', away: '#FFFFFF', bg: '#031216' },
  'Nantes':                { logo: club('nantes'),            home: '#FFD700', away: '#000000', bg: '#1a1300' },
  'Nice':                  { logo: club('nice'),              home: '#000000', away: '#CF0A2C', bg: '#0a0a0a' },
  'Paris FC':              { logo: club('paris-fc'),          home: '#003DA5', away: '#CC0000', bg: '#00041a' },
  'PSG':                   { logo: club('paris-saint-germain'),home:'#004170', away: '#DA291C', bg: '#00050d' },
  'RC Lens':               { logo: club('rc-lens'),           home: '#FFD700', away: '#CC0000', bg: '#1a1300' },
  'Strasbourg':            { logo: club('rc-strasbourg-alsace'),home:'#0070B8',away: '#FFFFFF', bg: '#00091a' },
  'Rennes':                { logo: club('rennes'),            home: '#DA291C', away: '#000000', bg: '#1a0203' },
  'Toulouse':              { logo: club('toulouse'),          home: '#6C2B8F', away: '#FFFFFF', bg: '#0e0016' },

  // Eredivisie
  'Ajax':                  { logo: club('ajax'),              home: '#CC0000', away: '#FFFFFF', bg: '#1a0000' },
  'AZ Alkmaar':            { logo: club('az-alkmaar'),        home: '#CC0000', away: '#FFFFFF', bg: '#1a0000' },
  'Excelsior Rotterdam':   { logo: club('excelsior-rotterdam'),home:'#CC0000', away: '#FFFFFF', bg: '#1a0000' },
  'FC Groningen':          { logo: club('fc-groningen'),      home: '#00954C', away: '#FFFFFF', bg: '#001a0d' },
  'FC Utrecht':            { logo: club('fc-utrecht'),        home: '#CC0000', away: '#FFFFFF', bg: '#1a0000' },
  'Feyenoord':             { logo: club('feyenoord'),         home: '#CC0000', away: '#FFFFFF', bg: '#1a0000' },
  'Fortuna Sittard':       { logo: club('fortuna-sittard'),   home: '#FFD700', away: '#000000', bg: '#1a1300' },
  'Go Ahead Eagles':       { logo: club('go-ahead-eagles'),   home: '#FFD700', away: '#000000', bg: '#1a1300' },
  'Heracles Almelo':       { logo: club('heracles-almelo'),   home: '#000000', away: '#FFFFFF', bg: '#0a0a0a' },
  'NAC Breda':             { logo: club('nac-breda'),         home: '#FFD700', away: '#000000', bg: '#1a1300' },
  'NEC Nijmegen':          { logo: club('nec-nijmegen'),      home: '#CC0000', away: '#000000', bg: '#1a0000' },
  'PEC Zwolle':            { logo: club('pec-zwolle'),        home: '#003DA5', away: '#FFFFFF', bg: '#00041a' },
  'PSV':                   { logo: club('psv'),               home: '#CC0000', away: '#FFFFFF', bg: '#1a0000' },
  'SC Heerenveen':         { logo: club('sc-heerenveen'),     home: '#003DA5', away: '#FFFFFF', bg: '#00041a' },
  'Sparta Rotterdam':      { logo: club('sparta-rotterdam'),  home: '#CC0000', away: '#FFFFFF', bg: '#1a0000' },
  'Twente':                { logo: club('twente'),            home: '#CC0000', away: '#FFFFFF', bg: '#1a0000' },
  'Volendam':              { logo: club('volendam'),          home: '#FF6600', away: '#000000', bg: '#1a0a00' },

  // Portugal
  'Benfica':               { logo: club('benfica'),           home: '#CC0000', away: '#FFFFFF', bg: '#1a0000' },
  'FC Porto':              { logo: club('fc-porto'),          home: '#004899', away: '#FFFFFF', bg: '#00031a' },
  'Sporting CP':           { logo: club('sporting-cp'),       home: '#006600', away: '#FFFFFF', bg: '#001400' },
  'SC Braga':              { logo: club('sc-braga'),          home: '#CC0000', away: '#FFFFFF', bg: '#1a0000' },
  'Alverca':               { logo: club('alverca'),           home: '#CC0000', away: '#FFFFFF', bg: '#1a0000' },
  'Arouca':                { logo: club('arouca'),            home: '#FFD700', away: '#000000', bg: '#1a1300' },
  'Estoril':               { logo: club('estoril'),           home: '#FFD700', away: '#000000', bg: '#1a1300' },
  'Famalicão':             { logo: club('famalicao'),         home: '#003DA5', away: '#FFFFFF', bg: '#00041a' },
  'Gil Vicente':           { logo: club('gil-vicente'),       home: '#000000', away: '#FFFFFF', bg: '#0a0a0a' },
  'Rio Ave':               { logo: club('rio-ave'),           home: '#006600', away: '#FFFFFF', bg: '#001400' },
  'Santa Clara':           { logo: club('santa-clara'),       home: '#CC0000', away: '#FFFFFF', bg: '#1a0000' },
  'Vitória Guimarães':     { logo: club('vitoria-de-guimaraes'),home:'#FFD700',away:'#000000', bg: '#1a1300' },

  // Scotland
  'Celtic':                { logo: club('celtic'),            home: '#1A7A37', away: '#FFFFFF', bg: '#01140a' },
  'Rangers':               { logo: club('rangers'),           home: '#1B3A8A', away: '#FFFFFF', bg: '#000c1a' },
  'Aberdeen':              { logo: club('aberdeen'),          home: '#CC0000', away: '#FFFFFF', bg: '#1a0000' },
  'Hearts':                { logo: club('hearts'),            home: '#9A1B2F', away: '#FFFFFF', bg: '#130509' },
  'Hibernian':             { logo: club('hibernian'),         home: '#005000', away: '#FFFFFF', bg: '#001400' },
  'Kilmarnock':            { logo: club('kilmarnock'),        home: '#003DA5', away: '#FFFFFF', bg: '#00041a' },
  'Motherwell':            { logo: club('motherwell'),        home: '#FFD700', away: '#CC0000', bg: '#1a1300' },
  'Dundee United':         { logo: club('dundee-united'),     home: '#FF6600', away: '#000000', bg: '#1a0a00' },

  // Turkey
  'Galatasaray':           { logo: club('galatasaray'),       home: '#FF6600', away: '#CC0000', bg: '#1a0a00' },
  'Fenerbahce':            { logo: club('fenerbahce'),        home: '#FFD700', away: '#002B56', bg: '#1a1300' },
  'Besiktas':              { logo: club('besiktas'),          home: '#000000', away: '#FFFFFF', bg: '#0a0a0a' },
  'Trabzonspor':           { logo: club('trabzonspor'),       home: '#8B0000', away: '#004899', bg: '#120000' },
  'Basaksehir':            { logo: club('basaksehir'),        home: '#FF6600', away: '#003DA5', bg: '#1a0a00' },
  'Eyüpspor':              { logo: club('eyupspor'),          home: '#003DA5', away: '#FFFFFF', bg: '#00041a' },

  // Saudi Arabia
  'Al Hilal':              { logo: club('al-hilal'),          home: '#004B9C', away: '#FFFFFF', bg: '#00041a' },
  'Al Nassr':              { logo: club('al-nassr'),          home: '#FFD700', away: '#003DA5', bg: '#1a1300' },
  'Al Ahli':               { logo: club('al-ahli'),           home: '#006600', away: '#FFFFFF', bg: '#001400' },
  'Al Ittihad':            { logo: club('al-ittihad'),        home: '#FFD700', away: '#000000', bg: '#1a1300' },
  'Al Ettifaq':            { logo: club('al-ettifaq'),        home: '#003DA5', away: '#FFFFFF', bg: '#00041a' },
  'Al Fateh':              { logo: club('al-fateh'),          home: '#FFD700', away: '#006600', bg: '#1a1300' },

  // MLS
  'Inter Miami CF':        { logo: club('inter-miami-cf'),    home: '#F7B5CD', away: '#231F20', bg: '#1a0b11' },
  'LA Galaxy':             { logo: club('la-galaxy'),         home: '#00245D', away: '#FFD700', bg: '#00011a' },
  'LAFC':                  { logo: club('los-angeles-fc'),    home: '#000000', away: '#C39E6D', bg: '#0a0a0a' },
  'Atlanta United':        { logo: club('atlanta-united'),    home: '#80000A', away: '#000000', bg: '#120000' },
  'Portland Timbers':      { logo: club('portland-timbers'),  home: '#004812', away: '#FFFFFF', bg: '#001a07' },
  'Seattle Sounders':      { logo: club('seattle-sounders-fc'),home:'#5D9732',away: '#FFFFFF', bg: '#061200' },
  'New York City FC':      { logo: club('new-york-city-fc'),  home: '#6CABDD', away: '#FFFFFF', bg: '#030d1a' },
  'New York Red Bulls':    { logo: club('new-york-red-bulls'),home: '#ED1B23', away: '#FFFFFF', bg: '#1a0202' },
  'FC Cincinnati':         { logo: club('fc-cincinnati'),     home: '#003087', away: '#FE5000', bg: '#00021a' },
  'Nashville SC':          { logo: club('nashville-sc'),      home: '#ECE83A', away: '#1F1646', bg: '#1a1a00' },
  'Philadelphia Union':    { logo: club('philadelphia-union'),home: '#071B2C', away: '#B19B69', bg: '#030a0f' },
  'Columbus Crew':         { logo: club('columbus-crew'),     home: '#FEDE00', away: '#000000', bg: '#1a1500' },
  'Toronto FC':            { logo: club('toronto-fc'),        home: '#B81137', away: '#FFFFFF', bg: '#1a0208' },
  'Vancouver Whitecaps':   { logo: club('vancouver-whitecaps-fc'),home:'#009BC8',away:'#FFFFFF',bg:'#031419' },
  'CF Montréal':           { logo: club('cf-montreal'),       home: '#003DA5', away: '#FFFFFF', bg: '#00041a' },
  'Colorado Rapids':       { logo: club('colorado-rapids'),   home: '#862633', away: '#FFFFFF', bg: '#120507' },
  'Houston Dynamo':        { logo: club('houston-dynamo'),    home: '#FF6600', away: '#000000', bg: '#1a0a00' },
  'Sporting KC':           { logo: club('sporting-kansas-city'),home:'#002F65',away:'#FFFFFF', bg: '#00021a' },
  'Minnesota United':      { logo: club('minnesota-united-fc'),home:'#8CD2F4', away:'#231F20', bg: '#031419' },
  'Orlando City':          { logo: club('orlando-city'),      home: '#612B9B', away: '#FDE272', bg: '#0d0016' },

  // UCL / European extras
  'Club Brugge':           { logo: club('club-brugge'),       home: '#1A3A8A', away: '#000000', bg: '#000c1a' },
  'Bodo/Glimt':            { logo: club('bodo-glimt'),        home: '#FFD700', away: '#000000', bg: '#1a1300' },
  'Shakhtar Donetsk':      { logo: club('shakhtar'),          home: '#FF6600', away: '#000000', bg: '#1a0a00' },
  'Dinamo Zagreb':         { logo: club('dinamo-zagreb'),     home: '#0049A0', away: '#FFFFFF', bg: '#000c1a' },
  'Red Bull Salzburg':     { logo: club('salzburg'),          home: '#CC0000', away: '#FFFFFF', bg: '#1a0000' },
  'Fiorentina (UCL)':      { logo: club('fiorentina'),        home: '#522D8B', away: '#FFFFFF', bg: '#0d0016' },
}

export const TEAM_NAMES = Object.keys(TEAMS).sort()

// ── COMPETITIONS ──────────────────────────────────────────────
export const COMPETITIONS = {
  'UEFA Champions League':  { logo: comp('tournaments_uefa-champions-league'), color: '#001D62', bg: '#001230' },
  'UEFA Europa League':     { logo: comp('tournaments_uefa-europa-league'),    color: '#FF6B00', bg: '#1a0d00' },
  'UEFA Conference League': { logo: comp('tournaments_uefa-conference-league'),color: '#00A551', bg: '#001a0e' },
  'FIFA Club World Cup':    { logo: comp('tournaments_fifa-club-world-cup'),   color: '#004B9C', bg: '#00031a' },
  'FIFA World Cup 2026':    { logo: comp('tournaments_fifa-world-cup-2026'),   color: '#004B9C', bg: '#00031a' },
  'UEFA Nations League':    { logo: comp('tournaments_uefa-nations-league'),   color: '#003DA5', bg: '#00031a' },
  'UEFA Super Cup':         { logo: comp('tournaments_uefa-super-cup'),        color: '#001D62', bg: '#001230' },
  'CONMEBOL Libertadores':  { logo: comp('tournaments_conmebol-libertadores'), color: '#003DA5', bg: '#00031a' },
  'Premier League':         { logo: comp('england_english-premier-league'),    color: '#3D195B', bg: '#0d0014' },
  'FA Cup':                 { logo: comp('england_emirates-fa-cup'),           color: '#00294A', bg: '#000e1a' },
  'EFL Cup':                { logo: comp('england_efl-cup'),                   color: '#00A0C6', bg: '#001419' },
  'EFL Championship':       { logo: comp('england_efl-championship'),          color: '#6CABDD', bg: '#030d1a' },
  'FA Community Shield':    { logo: comp('england_fa-community-shield'),       color: '#3D195B', bg: '#0d0014' },
  'La Liga':                { logo: comp('spain_la-liga'),                     color: '#EE8707', bg: '#1a0c00' },
  'Copa del Rey':           { logo: comp('spain_copa-del-rey'),                color: '#AA151B', bg: '#1a0203' },
  'Supercopa de España':    { logo: comp('spain_supercopa-de-espana'),         color: '#AA151B', bg: '#1a0203' },
  'Bundesliga':             { logo: comp('germany_bundesliga'),                color: '#D3010C', bg: '#1a0000' },
  'DFB Pokal':              { logo: comp('germany_dfb-pokal'),                 color: '#000000', bg: '#0a0a0a' },
  'Serie A':                { logo: comp('italy_serie-a'),                     color: '#024494', bg: '#000b1a' },
  'Coppa Italia':           { logo: comp('italy_coppa-italia'),                color: '#009246', bg: '#001a09' },
  'Ligue 1':                { logo: comp('france_ligue-1'),                    color: '#DFFE00', bg: '#0d0d00' },
  'Eredivisie':             { logo: comp('netherlands_eredivisie'),            color: '#CC0000', bg: '#1a0000' },
  'Primeira Liga':          { logo: comp('portugal_portuguese-football-federation'), color: '#009B3A', bg: '#001a0b' },
}

export const COMPETITION_NAMES = Object.keys(COMPETITIONS)

export const MATCH_STAGES = [
  'Matchday', 'League Match', 'Group Stage', 'Round of 32',
  'Round of 16', 'Quarter Final', 'Semi Final', 'Final',
  'Play-Off', 'Cup Final', 'Super Cup', 'Community Shield',
]

export function getTeam(name) {
  return TEAMS[name] || null
}

export function getCompetition(name) {
  return COMPETITIONS[name] || null
}
